name: 'starter_dw'
version: '0.1.0'
source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ['macros']
log-path: "logs"
clean-targets: ["target", "dbt_modules"]

profile: "my-profile"

quoting:
    identifier: false
    schema: false

models:
    enabled: true        # configs defined here are applied to _all_ packages

    starter_dw:
        post-hook:
            - "grant select on {{ this }} to role bi_tool_role"

        base:
            schema: "_base"
        dw:
            customer:
                schema: "customer"
            date:
                schema: "dt"
            marketing:
                schema: "marketing"
            product:
                schema: "product"
            shop:
                schema: "shop"
            social:
                schema: "social"

    vars:
        # put variables for source data tables here:
        customers: source_data.account.customers
        skus: source_data.product.skus
        products: source_data.product.products
        brands: source_data.product.brands
        campaigns: source_data.marketing.campaigns
        orders: source_data.shop.orders

on-run-end:
    # make sure to give your BI tools access to all the tables dbt maintains:
    - "grant usage on schema {{ target.schema }} to role bi_tool_role;"
    - "grant select on all tables in schema {{ target.schema }} to role bi_tool_role"
    - "alter warehouse if exists dbt suspend;""
