-- (0) TURN OFF CASE SENSITIVITY
USE ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE;

-- (1) CREATE DATABASES
USE ROLE SYSADMIN;
CREATE DATABASE "FIVETRAN";
CREATE DATABASE "DW";
CREATE DATABASE "DW_DEV";

-- (2) CREATE WAREHOUSES
CREATE WAREHOUSE "FIVETRAN_WH"
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE "DBT_WH"
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

CREATE WAREHOUSE "TABLEAU_WH"
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD';

-- (3) CREATE ROLES
USE ROLE ACCOUNTADMIN;

CREATE ROLE "FIVETRAN_ROLE";
CREATE ROLE "DBT_ROLE";
CREATE ROLE "BI_TOOLS_ROLE";

GRANT ALL PRIVILEGES ON WAREHOUSE "FIVETRAN_WH" TO ROLE "FIVETRAN_ROLE";
GRANT ALL PRIVILEGES ON WAREHOUSE "DBT_WH" TO ROLE "DBT_ROLE";
GRANT ALL PRIVILEGES ON WAREHOUSE "TABLEAU_WH" TO ROLE "BI_TOOLS_ROLE";

GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE ON DATABASE "FIVETRAN" TO ROLE "FIVETRAN_ROLE";
GRANT USAGE ON DATABASE "FIVETRAN" TO ROLE "DBT_ROLE";

GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE ON DATABASE "DW" TO ROLE "DBT_ROLE";
GRANT USAGE ON DATABASE "DW" TO ROLE "BI_TOOLS_ROLE";

GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE ON DATABASE "DW_DEV" TO ROLE "DBT_ROLE";
GRANT USAGE ON DATABASE "DW_DEV" TO ROLE "BI_TOOLS_ROLE";

-- (4) CREATE USERS
CREATE USER "FIVETRAN_USER"
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = "FIVETRAN_ROLE"
  DEFAULT_WAREHOUSE = "FIVETRAN_WH"
  PASSWORD = 'PASSWORD'; -- Single quote!
GRANT ROLE "FIVETRAN_ROLE" TO USER "FIVETRAN_USER";

CREATE USER "DBT_USER"
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = "DBT_ROLE"
  DEFAULT_WAREHOUSE = "DBT_WH"
  PASSWORD = 'PASSWORD'; -- Single quote!
GRANT ROLE "DBT_ROLE" TO USER "DBT_USER";

CREATE USER "TABLEAU_USER"
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = "BI_TOOLS_ROLE"
  DEFAULT_WAREHOUSE = "TABLEAU_WH"
  PASSWORD = 'PASSWORD'; -- Single quote!
GRANT ROLE "BI_TOOLS_ROLE" TO USER "TABLEAU_USER";

USE ROLE SYSADMIN;
